### ISSUE TITLE
Stop writing temporary tilesets to the specs folder during the tests

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-tools#11]
If possible, use `writeCallback` or at least use OS temp directories.

**Comment by javagl** [comment]
With the new functionality of 0.2.0, it will be hard to avoid writing "any" files.

Part of the 0.2.0 functionality is to convert between (file,ZIP,3TZ,3DTILES) and (file,3TZ,3DTILES). Testing this functionality _requires_ a file system. In a few places, there already is something like
```
  afterEach(function () {
    SpecHelpers.forceDeleteDirectory(basicOutput);
  });
```
to clean things up. This is not yet done for _all_ written files, but could certainly be extended, if the goal was to work towards a state where the specs leave the directories "'clean', as if they had never been run".

So I don't think this is critical, but will leave it open for now...
