### ISSUE TITLE
How to merge multiple tileset.jsons into one

### ISSUE THREAD

**Issue by jingyangking** [CesiumGS/3d-tiles-tools#119]
I want to combine multiple tiles into one tile set, so I used this command ` npx 3d files tools merge - i/ Specs/data/mergeTilesets/Tilesetone - i/ Spec/data/mergeTilesets/sub/Tilesettwo - i/ Spec/data/mergeTilesets/sub/Tilesetthree - o/ Spec/data/mergeTilesets/output `, where tiles one, tiles two, and tiles three all have tiles set.json and multiple b3dms, but the result shows that tileset.json cannot be found. I am not sure why? I hope you can give me a reply, thank you!

**Comment by jingyangking** [comment]
Yes, what I want to implement is the first example you provided, but unfortunately, as I mentioned before, the corresponding tileset.json cannot be found. I'm not sure why this happened. Is it because I input too many files that caused this situation? Thank you!

**Comment by jingyangking** [comment]
You're right, I provided a specific file path as follows:`"E:\3Dmodelfile\3dtiles\ifctileset\one_ifctileset"`，其中的文件内容如下：
![image](https://github.com/CesiumGS/3d-tiles-tools/assets/112468121/45bc05d4-cd6e-40b7-801f-a2bc16a42a90)
The other tileset.json files are the same except for their names,
![image](https://github.com/CesiumGS/3d-tiles-tools/assets/112468121/965b7c86-c7fc-47e5-97b1-a1bde61b51ff)
but entering such a command resulted in an error message
![image](https://github.com/CesiumGS/3d-tiles-tools/assets/112468121/9609ddfe-1458-4436-8be6-3f3d73bf5b05)
I hope this can clarify what I want to express，thank you!

**Comment by javagl** [comment]
Right now, I cannot imagine what could be the reason for this error. 

When _each_ input directory contains a file that is called `tileset.json`, then this should be picked up automatically. 

If this does not work: Could you try to merge only _two_ tilesets (as a test), and give the full path to the `tileset.json` files, like this:

`... -i E:\3Dmodelfile\3dtiles\ifctileset\one_ifctileset\tileset.json ...`
`                                                        ^--file name here`

I tried out the `merge` function with some example tilesets, and could not yet reproduce this error message, **except** for cases where the input directory did **not** contain a `tileset.json` file...

**Comment by jingyangking** [comment]
Okay, I'll give it a try. Thank you for your reply!

**Comment by javagl** [comment]
If it doesn't work, I'd even go so far to create a branch with additional logging information, with details about where exactly it is trying to find that `tileset.json` file, and which files it _does_ find there instead. We should be able to figure out what's wrong here.

**Comment by jingyangking** [comment]
Thank you for your reply! I found an issue: the input path must be accurate, including uppercase and lowercase letters, while the output path does not have such strict requirements.
![image](https://github.com/CesiumGS/3d-tiles-tools/assets/112468121/9536236d-5bdb-4a46-acf1-6f9fbc705899)

**Comment by javagl** [comment]
To some extent, this may depend on the operating system, but I'd have to verify that. 

But in general, one should assume that the paths are _case-sensitive_.

**Comment by jo-chemla** [comment]
> There are two functionalities of the 3D Tiles Tools that are related to each other. (And I'm always mixing them up...)
> 
> These functions are `merge` and `combine`:
> 
> * `merge` creates a tileset, that still refers to the input tilesets (as external tilesets)
> * `combine` creates a tileset where external tilesets have been "inlined"
> 

Sorry for commenting on a closed thread, but a warm thanks for this detailed comparison of `merge` vs `combine`. It explains really simply the difference between both methods and probably could be added some place more permanent - maybe in the 3d-tiles-tools readme as-is, or as a link to this comment

**Comment by javagl** [comment]
@jo-chemla I agree that this could be clarified. 

On the one hand, my comment only added a little detail compared the [the current documentation of `combine`](https://github.com/CesiumGS/3d-tiles-tools/tree/6b29e7dc96d614bc4c294c497d6040b17281c6a9?tab=readme-ov-file#combine), but probably an _important_ detail - namely, that the external tilesets are "inlined". (In fact, `inline` might have been a better name for `combine`, and `merge` could then have been called `combine`, but ... all this is subjective, to some extent...)

There are a few pending updates/clarifications for the README, and I'll probably add them (including this one) in the next days.

**Comment by jo-chemla** [comment]
Understood, thanks for the details! Indeed, also in favor of this naming, but probably cannot be done as a somewhat aggressive breaking change.
