### ISSUE TITLE
No tileset.json found in input when one exists (when upgrading Cesium ION created 3D tiles)

### ISSUE THREAD

**Issue by joedjc** [CesiumGS/3d-tiles-tools#121]
Hi,

I'm using the branch "upgrade-cmpt" to upgrade a set of tiles to 1.1.

The tileset input has been generated in Cesium ION (asset id: 2555134). I have downloaded the tiles from Cesium ION and run them though the converter with the following command:

npx ts-node ./src/cli/main.ts upgrade -i [path to your tileset] -o [path to your tileset]/upgraded --targetVersion 1.1

I have done this successfully with other tilesets, but for this particular one one I receive an error:

ERROR (CLI): No tileset.json found in input
    err: {
      "type": "TilesetError",
      "message": "No tileset.json found in input",

However, I can see a tileset.json in the input folder, so i'm unsure why 3d-tiles-tools doesn't seem to recognise it.

**Comment by javagl** [comment]
A wild, quick guess, because this was also the reason for this message in [an issue that I just closed](https://github.com/CesiumGS/3d-tiles-tools/issues/119#issuecomment-2080696704): 

The input paths are _case-sensitive_. Could it be that the path that you gave as the `-i` parameter does not match the _actual_ path name in terms of uppercase/lowercase letters?

**Comment by joecusdin** [comment]
Thanks for the response @javagl - that was the issue

**Comment by joedjc** [comment]
Thanks for the reply Thanks for the reply @javagl - that was the issue

**Comment by javagl** [comment]
I'll take an internal note to update the README.md with a hint at the top, saying that these paths are case-sensitive. 

Linux users are usually more careful here. But on Windows, paths are usually _not_ case-sensitive, so this requirement may come as a surprise.

**Comment by joedjc** [comment]
Thanks. It was a basic mistake on my part…but actually what would have helped would have been if the error said “Path cannot be found” or something like that rather than the tileset.json was missing. That threw me slightly as I thought it was an issue with that particular file. May be worth considering.

Thanks again for the response

**Comment by javagl** [comment]
One difficulty for providing a "better" error message at that point is that the operation takes place on a certain level of abstraction. From the input, it creates a `TilesetSource` object. And this can either be a file-system-based one, or one that reads from, for example, a 3DTILES (SQLite-based) file, or ... from any other source, FWIW. So at the point where the message appears, it just says
`data = tilesetSource.get("tileset.json");`
and complains about that data not being found (but it does not know _where_ this is ... not found...)
