### ISSUE TITLE
Storage increase issue caused by b3dm to glb conversion

### ISSUE THREAD

**Issue by HerculesJL** [CesiumGS/3d-tiles-tools#123]
Hello！ I use the following commond to convert b3dm to glb, and the storage increase from 1475KB to 2081KB, is it normal? Is this normal? If not, how should it be resolved。
```
 npx 3d-tiles-tools convertB3dmToGlb -i .\Node_3941_-1.b3dm -o ./Node.glb
```
[Node_3941_-1.zip](https://github.com/CesiumGS/3d-tiles-tools/files/15195890/Node_3941_-1.zip)

**Comment by HerculesJL** [comment]
Thank you so much, I really appreciate your help.

**Comment by javagl** [comment]
I'll leave this open until the underlying issue is fixed, just to keep track of it.

**Comment by javagl** [comment]
While fixing this, I noticed another issue: Some _very_ old legacy B3DM data can contain GLB where the batch ID attribute is not called `"_BATCHID"` but `"BATCHID"` (without underscore). The one with the legacy name was already handled as an _input_ and properly converted into a feature ID. But when it had the legacy name, then it was not _removed_ properly (i.e. the resulting primitive then contained _both_ a `_FEATURE_ID_0` _and_ a `BATCHID` attribute)
