### ISSUE TITLE
glTF 2.0 Draco compression

### ISSUE THREAD

**Issue by benjaminabb** [CesiumGS/3d-tiles-tools#13]
Is it possible to apply draco compression to glTF 2.0 b3dms?

When using the draco branch, I just get "Binary glTF version is not 1".
With the 2.0-tools branch, this error occurs:
> $ node ./bin/3d-tiles-tools.js optimizeB3dm -i "[...].b3dm" -o ./output/optimized.b3dm -f --options -q
> [...]\3d-tiles-tools\tools\lib\isJson.js:34
>         });
>          ^
> SyntaxError: Unexpected token )

And after deleting the faulty line 34, the output is also "Binary glTF version is not 1".  Am I doing something wrong?

**Comment by javagl** [comment]
This should be resolved with version 0.2.0.

Upgrading from glTF 1.0 to glTF 2.0 is done internally, by the latest version of [`gltf-pipeline`](https://github.com/CesiumGS/gltf-pipeline). (This upgrade may not be possible for _all_ glTF 1.0 assets, but many of them).

Beyond that, the 3d-tiles-tools only wrap gltf-pipeline at this point. So calling something like
``` 
npx 3d-tiles-tools optimizeB3dm -i ./input.b3dm -o ./output.b3dm --options --draco.compressMeshes --draco.compressionLevel=9
```
will compress the B3DM with Draco (upgrading its GLB data to glTF 2.0, if it contains glTF 1.0 data)
