### ISSUE TITLE
Does you consider to add function that conver osgb to b3dm

### ISSUE THREAD

**Issue by FengFengmomo** [CesiumGS/3d-tiles-tools#141]
can you enhence the tools , support convert osgb to b3dm?

**Comment by javagl** [comment]
The 3D Tiles Tools are _generally_ working with 3D Tiles (and 3D Tiles content data). The scope of the 3D Tiles tools is _not_ any form of conversion/tiling from other formats. (There are just too many of them, and creating a _good_ conversion program for _any_ format into 3D Tiles is challenging.

You could try to export your model in a format that is supported by Cesium ion, and then upload it as described in https://cesium.com/platform/cesium-ion/3d-tiling-pipeline/ to create 3D Tiles data.
