### ISSUE TITLE
`3d-tiles-tools upgrade` --options flag not effective for `gltf-pipeline gltfUpgradeOptions`

### ISSUE THREAD

**Issue by jo-chemla** [CesiumGS/3d-tiles-tools#144]
Hi there, 

I'm trying to parse through every glb tile of a large tileset, trying to decompress textures which are compressed with KTX2. 
Note KTX2 decompression is not yet available within gltf-pipeline - see probable blockers in [this thread](https://github.com/donmccurdy/glTF-Transform/issues/591) for gltf-transform, and linked [root](https://github.com/KhronosGroup/Basis-Universal-Transcoders/issues/20) issue thread to enable support within `KhronosGroup/Basis-Universal-Transcoders` - so I'll do this by myself, but would need to explode every `glb` tile to `gltf + bin geometry + ktx2 texture`. 

I've been trying several iterations of the `upgrade` command with the `--options` flag passed to either `--separateTextures`, `--separate` to explode geometry and textures, or `--json` to convert gltf to glb but they all resulted in glb tiles - with packed geometry and textures. By reading through the code, it seems that the targetVersion has to be 1.0 for these `gltfUpgradeOptions` to be passed, but I feel like I'm misunderstanding how to process every tile with gltf-pipeline. 

Here are some example commands I've tested. Any help would be appreciated! Best regards,

```bash
npx 3d-tiles-tools upgrade -i .\tilesetRoot.json -o .\separate-tilesetRoot.json --targetVersion 1.0 --options --separate
npx 3d-tiles-tools upgrade -i .\tilesetRoot.json -o .\separate-tilesetRoot.json --targetVersion 1.0 --options --separateTexture
npx 3d-tiles-tools upgrade -i .\tilesetRoot.json -o .\json-tilesetRoot.json --targetVersion 1.0 --options --json
```

**Comment by javagl** [comment]
These `--options` are intended for a very narrow use-case. (And maybe that could be made clearer in the description). They are only passed to the `gltf-pipeline` for the case where the glTF that is contained in B3DM- or I3DM files is supposed to be upgraded from glTF 1.0 to glTF 2.0. (This in itself is only possible for very few cases - basically, cases where ~"the GLSL shader code (that was still stored in glTF 1.0!) has a certain structure"). So when you have a veeery old tileset, where the B3DMs still contain glTF 1.0 data, then the `upgrade` (with `--targetVersion 1.0`, the default) will _try_ to convert this glTF 1.0 into glTF 2.0. And for rare, special cases, it can be useful to pass in additional `--options` for the conversion.

Or more focussed on your question: There is no built-in mechanism for doing arbitrary invovations of `gltf-pipeline` (and consequently, no mechanism to pass `--options` to such an invocation).

**But...** in a more abstract form, this is a common use-case: "Perform operation X on every tile content". This can often be done with a few lines of custom code. And an approach for generalizing this was ... actually drafted even in one of the first versions of the 3D Tiles Tools. Namely, the concept of a "pipeline". Unfortunately, this was never really settled/solidified (even though it could be _remarkably_ powerful). But fortunately, one of the "initial draft" functionalities that still _does_ work could be helpful here:

Put this into some `pipeline.json`:
```
{
  "input": "C:/data/glb/tileset.json",
  "output": "C:/data/gltf/tileset.json",
  "tilesetStages": [
    {
      "name": "ConvertGlbToGltf",
      "contentStages": [
        {
          "name": "separateGltf"
        }
      ]
    }
  ]
}
```
and run this with
`npx 3d-tiles-tools pipeline -i .\pipeline.json`

It will read the input, and convert each `.glb` into a `.gltf`+resources (updating the `content.uri`s accordingly).

(The "magic" here is that `"name": "separateGltf"`, which is sort of a "predefined command". Generalizing this _properly_, and defining a real "file format" for the pipelines, including a JSON schema and such, is ... a long-term-maybe 'TODO'...)

---

I'm still curious about how you intend to do the next step. I don't know how much tooling exists, in NodeJS or in general, for the required steps:

- Uncompress KTX2 
  - Sure, there is `ktx transcode --target rgba8 example.ktx2 output.raw` to convert the KTX data into raw RGBA pixel values, but ... then you'd still have to convert raw RGBA pixel values into PNG. Yeah, it's doable (I just tried this out (in Java), and ... yeah, there are the usual quirks (with the image being flipped vertically and such)), but ... a bit of a hassle...
- Update the glTF files to now refer to these PNGs (even though that might be doable with some glTF-Transform trickery...)
- Convert the resulting `.gltf` files back into `.glb` (there is no "opposite" of `separateGltf` in the current state of that "pipeline" support 😬 )

The easiest approach would be - **iff** glTF-Transform supported decompressing KTX2 - to just use the following skeleton for "generic tile content processing". In that callback that currently contains the log message, you could ...

- create a glTF-Transform `Document` from the `sourceEntry.value` (GLB data)
- twiddle with that document - i.e. apply the hypothetical `transform(ktxToPng())`, if this existed...
- write the resulting document into a buffer, and return this as the `targetEntry.value`

```javascript
import { TilesetEntry } from "./src/tilesets";
import { BasicTilesetProcessor } from "./src/tools";

async function example() {

  const source = "./input/tileset.json";
  const target = "./output/tileset.json";
  const overwrite = true;

  const tilesetProcessor = new BasicTilesetProcessor();
  await tilesetProcessor.begin(source, target, overwrite);

  // Process all entries that are tile content
  await tilesetProcessor.processTileContentEntries(
    (uri: string) => uri,
    async (
      sourceEntry: TilesetEntry,
      type: string | undefined
    ): Promise<TilesetEntry> => {
      console.log("In processTileContentEntries");
      console.log("  name:" + sourceEntry.key);
      console.log("  type: " + type);
      const targetEntry : TilesetEntry = {
        key: sourceEntry.key,
        value: sourceEntry.value
      }
      return targetEntry;
    }
  );
  await tilesetProcessor.end();
}

example();
```

It might even be possible to come up with some hacky solution here, like an `fs.writeFileSync(..."tempInput")`, followed by a (CLI!) call to `ktx transcode`, and then some `fs.readFileSync("tempOutput")` to read the RGBA pixels, and do some `sharp` call to convert these pixels to PNG and sneak the result back into the glTF-Transform `Texture` - but this could only be _remotely_ reasonable iff (if and only if) all this was supposed to be a one-shot operation for one specific tileset...

**Comment by jo-chemla** [comment]
Once again, thank you so much for all these details, really full of insights. 
This is indeed a once-in-a-lifetime workflow that shall not be applied in production, but only to one tileset we did receive that do not match our current expectations. 

Combining `3d-tiles-tools tilesetProcessor.processTileContentEntries` with `gltf-transform document.transform` (with a custom transform) is indeed exactly the way to go. I gave it a shot, and avoided CLI calls as much as possible - but still relied quite heavily on node synchronous operations. 

Note the ktx pipeline can directly export a ktx file to image file via the `extract` CLI method. There also seem to be js bindings to libktx, see [here](https://github.khronos.org/KTX-Software/ktxjswrappers/libktx_js.html) and [there](https://github.com/KhronosGroup/KTX-Software/discussions/782) as wasm, but seem not yet very straightforward.

The pipeline now looks like the following: 
 - Create tilesetProcessor for source/target args, then loop over each mesh tile via `tilesetProcessor.processTileContentEntries`
 - first call to `GltfUtilities.upgradeGlb` since gltf-transform can only process version 2.0 gltf, and write to file
 - then `io.read` that 2.0 document, and `transform` with a custom pipeline that
 - loops over textures, and for those with ktx2 mimeType, write image to disk so `ktx` CLI can process 
 - call `ktx extract TEMP_KTX2_TEX TEMP_PNG_TEX` to write to png
 - finally read that temporary png image and final call to `texture.setImage(pngImg)` so the gltf-transform Document has a new png texture

I'm mostly done with the below code - fighting with sharp when trying to use cloneDocument, seems to be due to an issue that was fixed by a release of gltf-transform that is more recent that the one used in 3d-tiles-tools repo. Again, thanks a lot for your help!

<details>
  <summary>Complete code</summary>
  
  ```js

import path from "path";
import fs from 'fs';
import { spawn, spawnSync } from 'child_process';

// cesium 3d-tiles-tools
import {
    TilesetEntry,
    BasicTilesetProcessor,
    TilesetUpgrader,
    GltfUtilities
} from "3d-tiles-tools";
// import GltfPipeline from "gltf-pipeline";
// donmccurdy gltf-transform
import { Document, NodeIO } from '@gltf-transform/core';
import { ALL_EXTENSIONS } from '@gltf-transform/extensions';
import draco3d from 'draco3dgltf';
import { cloneDocument } from '@gltf-transform/functions';
// import { read as ktxread, write as ktxwrite } from 'ktx-parse';


const TEMP_KTX2_TEX = 'temp_tile_20_fp.ktx2'
const TEMP_PNG_TEX = 'temp_tile_20_fp.png'

async function main() {

    const source_ = "L:/JOBS/tilesetRoot.json";
    const target = "./output/tileset.json";
    const overwrite = true;

    const source = path.normalize(source_).replaceAll('\\', '/')
    console.log('source_ vs source', source_, source)
    const tilesetProcessor = new BasicTilesetProcessor();
    await tilesetProcessor.begin(source, target, overwrite);
    const sourceDir = determineTilesetDirectoryName(source)
    const targetDir = determineTilesetDirectoryName(target)

    // Configure I/O.
    const io = new NodeIO()
        .registerExtensions(ALL_EXTENSIONS)
        .registerDependencies({
            'draco3d.decoder': await draco3d.createDecoderModule(), // Optional.
            'draco3d.encoder': await draco3d.createEncoderModule(), // Optional.
        });

    // Using 3d-tiles-tools tilesetProcessor.processTileContentEntries 
    // Process all entries that are tile content
    await tilesetProcessor.processTileContentEntries(
        (uri: string) => uri,
        async (
            sourceEntry: TilesetEntry,
            type: string | undefined
        ): Promise<TilesetEntry> => {
            console.log("In processTileContentEntries");
            console.log("  name:" + sourceEntry.key);
            console.log("  type: " + type);
            // console.log("  value: " + sourceEntry.value);

            if (type == 'CONTENT_TYPE_GLB') {

                // Can use gltf-transform here to glb to gltf and process the gltf
                const tile_fp = path.join(sourceDir, sourceEntry.key);

                const glbBuffer = sourceEntry.value;

                const upgradedOutputBuffer = await GltfUtilities.upgradeGlb(glbBuffer, { targetVersion: "2.0" })
                const tile_20_fp = path.format({
                    dir: path.join(targetDir, path.parse(sourceEntry.key).dir),
                    name: path.parse(sourceEntry.key).name + '-2.0',
                    ext: '.glb',
                }).replaceAll('\\', '/');
                console.log(`  - writing upgraded 2.0 gltf to ${tile_20_fp}`)
                fs.writeFileSync(tile_20_fp, upgradedOutputBuffer);
                console.log('  done upgrading glb to 2.0 so gltf-transform can process')
                // result.glb;

                const sourceDocument = await io.read(tile_20_fp);
                // const targetDocument = cloneDocument(sourceDocument);
                const targetDocument = sourceDocument;
                await targetDocument.transform(
                    customTransform({}),
                )
                // Other transformations available: 
                // prune(), // Remove unused nodes, textures, or other data.
                // dedup(), // Remove duplicate vertex or texture data, if any.
                // draco(), // Compress mesh geometry with Draco.
                // // Convert textures to WebP (Requires glTF Transform v3 and Node.js).
                // textureCompress({
                //     encoder: sharp,
                //     targetFormat: 'webp',
                //     resize: [1024, 2024],
                // }),

                const outputGlb = await io.writeBinary(targetDocument);
                // console.log('outGlb', outputGlb)
                // console.log('sourceEntry.value', sourceEntry.value)
                const targetEntry: TilesetEntry = {
                    key: sourceEntry.key,
                    value: Buffer.from(outputGlb)
                }
                return targetEntry;
            }

            const targetEntry: TilesetEntry = {
                key: sourceEntry.key,
                value: sourceEntry.value
            }
            return targetEntry;
        }
    );
    await tilesetProcessor.end();

    // Delete temporary files
    [TEMP_KTX2_TEX, TEMP_KTX2_TEX].forEach(
        fp => fs.unlink(
            fp,
            function (err) {
                if (err) return console.log(err);
                console.log(`file ${fp} deleted successfully`);
            }
        )
    )
}

// Custom transform: enable/disable backface culling.
function customTransform(options: any) {
    return (document: Document) => {
        for (const texture of document.getRoot().listTextures()) {
            // material.setDoubleSided(!options.cull);
            console.log('  - texture mimeType', texture.getMimeType())
            if (texture.getMimeType() == 'image/ktx2') {
                // Explore js bindings for libktx by khronos group to avoid CLI call - requires wasm build
                // https://github.khronos.org/KTX-Software/ktxjswrappers/libktx_js.html 
                // https://github.com/KhronosGroup/KTX-Software/discussions/782

                const image = texture.getImage();
                if (image) {
                    // const ktx_input = ktxread(image);
                    // const name = texture.getURI() || texture.getName();
                    // const ktx_output = ktxwrite(ktx_input)
                    fs.writeFileSync(TEMP_KTX2_TEX, image);
                    console.log('  - ktx texture written to disk so ktx CLI can process to png', TEMP_KTX2_TEX)
                    // texture.setImage(ktx_output);

                    const ktxCmd = spawnSync('ktx', ['extract', TEMP_KTX2_TEX, TEMP_PNG_TEX]);
                    // console.log(`stderr: ${ktxCmd.stderr.toString()} \nstdout: ${ktxCmd.stdout.toString()}`);
                    console.log('  ktx texture converted to png to ', TEMP_PNG_TEX)

                    const pngImg = fs.readFileSync(TEMP_PNG_TEX)
                    texture.setImage(pngImg);
                    texture.setMimeType('image/png');
                    console.log('  glb tile ktx2 texture replaced with png')
                }
            }
        }
    };
}


function determineTilesetDirectoryName(tilesetName: string) {
    const n = tilesetName.toLowerCase();
    if (n.endsWith(".json") || n.endsWith(".3tz") || n.endsWith(".3dtiles")) {
        return path.dirname(tilesetName);
    }
    return tilesetName;
}

main();


// Could also choose upgrade whole tileset to 2.0 (so gltf-transform can parse it)
// As well as explode glb to gltf + ktx2 + draco bin geometry for easier processing
// But these are done via the script rather than CLIs
// const gltfUpgradeOptions = undefined;
// const targetVersion = "1.1";
// const tilesetUpgrader = new TilesetUpgrader(
//   targetVersion,
//   gltfUpgradeOptions
// );
// await tilesetUpgrader.upgrade(currentInput, currentOutput, overwrite);


  ```
</details>

**Comment by javagl** [comment]
OK, that looks like a fleshed-out version of that "hacky" solution that I mentioned, with that "hacky" part mainly being the necessity to call the KTX CLI tool.

I only have a rough understanding/memory of the current pain points:

About sharp: 
I remember that I once stumbled over some obscure error messages related to `sharp`. It was something that involved "Could not load the "sharp" module..." messages. And it was related to some version incompatibilty, caused by some _native_ library that `sharp` is using under the hood, and that somehow ~"can only be loaded in one version", meaning that it shows up when there are _two_ different `sharp` versions in the dependency tree. IIRC, I stumbled over https://github.com/lovell/sharp/issues/3870#issuecomment-1833121113 and (even though I'm on Windows) helplessly downgraded _some_ version of sharp _somewhere_, and it worked...

About the CLI call: 
There once had been JS bindings for KTX. And technically, they are still there. But the documentation at https://github.khronos.org/KTX-Software/ktxjswrappers/index.html says that they are deprectated. But I know that they _recently_ have been extended, _somewhere_ in the context of https://github.com/KhronosGroup/glTF-Compressor/tree/main/source/libs . But I think that these changes did not yet make their way back into the main repo. So ... the **tl;dr** of all these 'but's': The KTX-Software repo (and mainly the bindings) may ... require some work. 
(I started cleaning up the Java bindings a while ago, at https://github.com/KhronosGroup/KTX-Software/pull/886 , but ... have to juggle with priorities here...)

The 3D Tiles Tools actually contain a [`KtxUtility`](https://github.com/CesiumGS/3d-tiles-tools/blob/2a47318d44b10adb28797d9db0225d52e77d3bea/src/ktx/ktx/KtxUtility.ts) class (used in some of the [`GltfTransform....` utility classes](https://github.com/CesiumGS/3d-tiles-tools/tree/b6b104c9dc726017a0746e66badcfd13a71f6c97/src/tools/contentProcessing)). But being based on the BinomialLLC encoder, this currently only offers **en**coding into KTX, and not **de**coding. Maybe it will be extended in the future....

**Comment by javagl** [comment]
(A small aside: It's not entirely clear why you are _writing_ the glTF 2.0 data into _files_. It should be possible to just read the GLB data with `await io.readBinary(someBuffer);`. But I'd have to read the code more thoroughly...)

**Comment by jo-chemla** [comment]
Thanks again for getting back. 
 - indeed you last aside matched this morning's shower thought - no need to write upgraded 2.0 glb to disk thanks to `io.readBinary(someBuffer);`. I'm starting to grasp better how these tileset and mesh processing libraries do work, thanks a lot for all these pointers
 - Also exact that my sharp errors seem to come from having two sharp versions installed in the project - one from gltf-transform and one from 3d-tiles-tools. I can actually avoid the `cloneDocument(sourceDocument)` since the operations I'm doing do not seem to happen in place, so the errors fades away. 
 - also thanks for the context around the ktx js bindings. 

I just edited the above code snippet to fix minor errors. Last thing I need to be doing is that the document still have the `KHR_texture_basisu` listed as `extensionsRequired` and `extensionsUsed` although the texture is now png, and I cannot find the way to do it via gltf-transform utility methods. Will investigate a bit more and consider this done.
