### ISSUE TITLE
Set up CI with GitHub actions

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles-tools#19]
This should be easy, but opened to keep track of it: There should be a GitHub action for CI.

Most of the build infrastructure was taken from the 3d-tiles-validator, so it should mainly be a matter of copying the [validator CI file](https://github.com/CesiumGS/3d-tiles-validator/blob/0e43590d2f8c784137b630032043420c58e94ee4/.github/workflows/ci.yml) here.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles-tools/pull/26
