### ISSUE TITLE
From single sided to double sided materials 

### ISSUE THREAD

**Issue by geolocus** [CesiumGS/3d-tiles-tools#2]
Is it possible to add/adjust code for single sided materials to become double sided?

**Comment by javagl** [comment]
The `3d-tiles-tools` do _very_ few operations on the glTF itself. Most of the glTF work is delegated to [`gltf-pipeline`](https://github.com/CesiumGS/gltf-pipeline) right now. Integrating other "glTF modification libraries" is on the radar, but most of them won't offer this operation "out of the box". 

If the goal was to integrate this functionality in the 3d-tiles-tools, we'd have to think about how exactly it should be offered. It could be one operation, similar to the current `optimize*` family of operations. But ... it's a very _simple_ operation, and a very _specific_ operation, so I'm a bit on the fence of whether it's worth integrating that here.

I'm slightly leaning towards closing this issue, but maybe one ("important") question before doing so:

Was the intention to apply this to B3DM/I3DM files? 
Or should it be applied to files that already _are_ GLB?

(For the latter, it may be easier and more reasonable to just batch-process them with one of the existing glTF libraries that may be used for this sort of operation...)
