### ISSUE TITLE
Installation fails due to old better-sqlite3 dependency on Node 19.

### ISSUE THREAD

**Issue by here-abarany** [CesiumGS/3d-tiles-tools#23]
This package fails to install due to the old better-sqlite3 dependency. Since this is now a dependency of 3d-tiles-validator, installation of that package fails as well when using the latest HEAD. The dependency should be updated to 8.0.1 to match.

See also CesiumGS/3d-tiles-validator#245

**Comment by javagl** [comment]
Thanks for this hint. I have opened a PR for the update at https://github.com/CesiumGS/3d-tiles-tools/pull/25 , but still have to...

- test this from a freshly cloned state, with different node versions and
- test this in the context of CI (see https://github.com/CesiumGS/3d-tiles-tools/issues/19 )

Also, I think that it should now be possible to _remove_ this dependency in the validator. It should no longer depend on `better-sqlite3` _directly_ (but only indirectly, via the `3d-tiles-tools`)

**Comment by here-abarany** [comment]
Thanks!
