### ISSUE TITLE
Runtime error thrown from WASM part when encoding KTX

### ISSUE THREAD

**Issue by javagl** [CesiumGS/3d-tiles-tools#77]
The [`KtxUtility`](https://github.com/CesiumGS/3d-tiles-tools/blob/ae5c38d740e8e745c458f65201e0e8428f1a611a/src/ktx/KtxUtility.ts#L61) class is a thin convenience layer around the BinomialLLC Basis Universal encoder. It mainly offers that function `convertImageData`, where the caller can throw in some arbitrary image data, and receive the resulting KTX image data. This is hiding all the nitty-gritty bits of (compiling!)/loading/initializing/configuring the underlying WASM module. 

When calling this method many (**many**) times, it eventually causes a RuntimeError to be thrown from the WASM part:

> RuntimeError: Aborted(). Build with -sASSERTIONS for more info.

(+ some stack trace into the WASM). The tooling and debugging possibilities around WASM are ... ... ... have a lot of room for improvement. But the observed behavior is a hint at ~"some sort of memory leak".

The WASM module has a `delete()` function. The documentation of this function is:
```
/*
 * Just kidding. It is not documented...
 */
```
But calling this function at the right place and time might resolve this issue.

**Comment by javagl** [comment]
From a quick test, the commit https://github.com/CesiumGS/3d-tiles-tools/pull/75/commits/c0315a00046ab79341edcd8b375f92a980d0aefa that is part of https://github.com/CesiumGS/3d-tiles-tools/pull/75 should fix this issue.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/3d-tiles-tools/pull/75
