### ISSUE TITLE
Add a cleanup stage

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-tools#8]
Similar to the automatic clean up stages in https://github.com/AnalyticalGraphicsInc/gltf-pipeline, `3d-tiles-tools/tools` could have a stage to perform any needed cleanup on the tileset. This may include adding a `_3DTILESDIFFUSE` semantic to the glTFs to support different color blend modes in Cesium: https://github.com/AnalyticalGraphicsInc/cesium/pull/4451

**Comment by javagl** [comment]
If this issue is still relevant, it may be necessary to add further details about what "cleanup" should refer to.
