### ISSUE TITLE
b3dmToGlb leaves ending padding bytes in glb file

### ISSUE THREAD

**Issue by verhoevenv** [CesiumGS/3d-tiles-tools#82]
For example, on the BoxTextured GLB sample model (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTextured/glTF-Binary), packing and unpacking creates a different GLB:

```
$ npx 3d-tiles-tools glbToB3dm -i BoxTextured.glb -o BoxTextured.b3dm
$ npx 3d-tiles-tools b3dmToGlb -i BoxTextured.b3dm -o BoxTexturedOut.glb
$ stat -c "%s %n" BoxTextured*.glb
6540 BoxTextured.glb
6544 BoxTexturedOut.glb
```

According to the Khronos glTF Validator website, the resulting GLB file is valid with warnings. Unfortunately some other tools and validators are less lenient and reject a GLB that doesn't conform to its own stated length.

The b3dm spec states

> The actual binary glTF data does not include possible trailing padding bytes. Clients must take into account the length from the [binary glTF header](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#binary-gltf-layout), and use this length to determine the part of the tile data that actually represents the binary glTF.

so I would argue that 3d-tiles-tools should also strip out these bytes.

Thoughts?

If this looks valid, I think I can create a pull request sometime in the coming weeks.

**Comment by javagl** [comment]
This might now already be fixed with https://github.com/CesiumGS/3d-tiles-tools/pull/83 . The "roundtrip" of GLB->B3DM->GLB should now result in a GLB file without the padding bytes.
